---
title: "RIME_VVIQ_analysis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

## load packages, helpers, and constants
```{r load packages, echo=FALSE}
library(tidyverse)
library(here)
library(R.matlab)
library(reticulate)
library(ggpubr)
library(rstatix)
library(qapi)
library(ggpubr)
library(forcats)
```
```{r helpers, echo=FALSE}
#define some helpers
resp_labelsR <- function(resp)
{
  ret <- 0
  if(resp==0){
    ret <- "nan"
  }
  if(resp==1){
    ret <- "forgot"
  }
  if(resp==2){
    ret <- "gist"
  }
  if(resp==3){
    ret <- "mod. vivid"
  }
  if(resp==4){
    ret <- "v. vivid"
  }
  return(ret)
}

#for use with PT data
resp_labelsPT <- function(resp)
{
  ret <- 0
  if(resp==0){
    ret <- "nan"
  }
  if(resp==1){
    ret <- "sure new"
  }
  if(resp==2){
    ret <- "likely new"
  }
  if(resp==3){
    ret <- "likely old"
  }
  if(resp==4){
    ret <- "sure old"
  }
  return(ret)
}

#confidence rating
confidence_rating <- function(resp)
{
  ret <- 0
  if(resp==0){
    ret <- 0
  }
  if(resp==1){
    ret <- 1
  }
  if(resp==2){
    ret <- 0
  }
  if(resp==3){
    ret <- 0
  }
  if(resp==4){
    ret <- 1
  }
  return(ret)
}

#label the repetition status of an image
#I'm sorry but I need to rant about this; WHY are the condition IDs A) not saved in their own coulmn, B) stored in DIFFEERENT PARTS OF THIS STRING. WHO DID THIS
##### fixed in preprocessing, this function is no longer relevant
cond_labels <- function(conID)
{
  ret <- 0
  if(substr(conID,2,2)=="L"){
    ret <- "New"
  } else if(substr(conID,3,3)=="D") {
    ret <- "Foil"
  } else if(substr(conID,3,3)=="I") {
    ret <- "Old"
  }
  return(ret)
}

#get retrieval labels
ret_labels <- function(conID)
{
  ret <- 0
  if(substr(conID,2,2)=="R"){
    ret <- "Retrieved"
  } else if(substr(conID,2,2)=="N") {
    ret <- "Not Retrieved"
  } else {
    ret <- "Not Shown"
  }
  return(ret)
}

#add vividness labels to posttestdf
#I'm aware this isnt tidy but this dataset was not built for tidyverse so
vivid_labels <- function(posttestdf,retrievaldf)
{
  posttestdf <- mutate(posttestdf,vividnessLabel=rep(0,length(posttestdf$conID)))
  for(i in seq(from=1,to=length(retrievaldf$conID)))
  {
    targetID <- retrievaldf$conID[i]
    targetTrials <- which(posttestdf$conID==targetID)
    posttestdf$vividnessLabel[posttestdf$conID==retrievaldf$conID[i]] =
      retrievaldf$respLabels[i]
  }
  return(posttestdf)
}

#compute standard error of the mean
sem <- function(x) sd(x)/sqrt(length(x))

```
```{r constants, echo=FALSE}
nsubj <- 64
ntrialsR <- 192
ntrialsPT <- 288
numquestions <- 16
retrievaldf <- data.frame()
posttestdf <- data.frame()
VVIQdf <- data.frame()
print(paste("nsubj =",as.character(nsubj)))
```
```{r load data, echo=FALSE}
### loading data ###
workingDir <- here("~/Desktop/RIME_VVIQ")
for (isubj in seq(from=1, to=nsubj))
{
  if(isubj<10){
    subjStr <- paste("0",as.character(isubj),sep="")
  } else {
    subjStr <- as.character(isubj)
  }
  subjDir <- paste(workingDir,"Data",subjStr,sep="/")
  retrievalmat <- readMat(here(paste(subjDir,"analysisFiles/retData.mat",sep="/")))
  posttestmat <- readMat(here(paste(subjDir,"analysisFiles/ptData.mat",sep="/")))
  retrievalmat <- as.data.frame(lapply(retrievalmat,unlist,use.name=FALSE))
  posttestmat <- as.data.frame(lapply(posttestmat,unlist,use.name=FALSE))
  ## add some much needed labeling to the data
  retrievalmat <- mutate(retrievalmat,respLabels=unlist(lapply(retrievalmat$response,resp_labelsR)))
  retrievalmat <- mutate(retrievalmat,condLabels=unlist(lapply(retrievalmat$conID,cond_labels)))
  retrievalmat <- mutate(retrievalmat,retLabels=unlist(lapply(retrievalmat$conID,ret_labels)))
  retrievalmat <- mutate(retrievalmat,subjID=as.factor(rep(isubj,ntrialsR)))
  
  posttestmat <- mutate(posttestmat,respLabels=unlist(lapply(posttestmat$response,resp_labelsPT)))
  posttestmat <- mutate(posttestmat,condLabels=unlist(lapply(posttestmat$conID,cond_labels)))
  posttestmat <- mutate(posttestmat,retLabels=unlist(lapply(posttestmat$conID,ret_labels)))
  posttestmat <- mutate(posttestmat,subjID=as.factor(rep(isubj,ntrialsPT)))
  retrievaldf <- rbind(retrievaldf,retrievalmat)
  posttestdf <- rbind(posttestdf,posttestmat)
  
  ##VVIQ stuff
  VVIQdat <- read.table(file=
                paste(subjDir,"/VVIQ/sub",subjStr,"_VVIQ_resp.csv",sep=""),
                sep=",",header=TRUE,skip=5)
  VVIQdat$question <- NULL
  VVIQdat <- mutate(VVIQdat,subjID=as.factor(rep(isubj,numquestions)))
  VVIQdf <- rbind(VVIQdf,VVIQdat)
}
```

## Summary Data - are participants able to do the task?

## Vividness Rating plots
```{r vividness, echo=FALSE}
## look at responses on vividness test
labs <- (c(.1,.2,.3,.4)*length(retrievaldf$response))
ggplot(retrievaldf,aes(x=response)) + geom_histogram(color='black',fill='blue',bins=5) + xlab('vividness rating') +
  ggtitle("Distribution of Vividness Ratings") + 
  scale_y_continuous(name="% of responses",breaks=labs,labels=100*c(.1,.2,.3,.4))
#group by face object and scene images
retrievaldf %>% group_by(stimulus) %>% summarise_at(vars(response),list(mean_rating=mean)) %>%
  ggplot(aes(x=stimulus,y=mean_rating)) + geom_bar(stat="identity") + 
  ggtitle("Mean Vividness Rating by Stimulus Type")
```

## Post Test plots

```{r post test, echo=FALSE}
## look at acc on post test
#posttestdf %>% group_by(subjID) %>% summarise_at(vars(acc),list(mean_acc=mean)) %>%
#   ggplot(aes(x=subjID,y=mean_acc)) + geom_point() + 
#   ggtitle("Mean Post test Accuracy for each Subject")
# ## look at acc on post test split by stimulus type
# posttestdf %>% group_by(stimulus) %>% summarise_at(vars(acc),list(mean_acc=mean)) %>%
#   ggplot(aes(x=stimulus,y=mean_acc)) + geom_bar(stat="identity") + 
#   ggtitle("Mean Post Test Accuracy by Stimulus Type")
# ## look at acc on post test split by condition
# posttestdf %>% group_by(condLabels) %>% summarise_at(vars(acc),list(mean_acc=mean)) %>%
#   ggplot(aes(x=condLabels,y=mean_acc)) + geom_bar(stat="identity") + 
#   ggtitle("Mean Post Test Accuracy by Memory Condition")
# ## look at acc on post test split by retrieval condition
# posttestdf %>% group_by(retLabels) %>% summarise_at(vars(acc),list(mean_acc=mean)) %>%
#   ggplot(aes(x=retLabels,y=mean_acc)) + geom_bar(stat="identity") + 
#   ggtitle("Mean Post Test Accuracy by Retrieval Status")
## lets get dprime

'%!in%' <- Negate('%in%')
dprimedf <- data.frame(matrix(ncol=3))
colnames(dprimedf) <- c('subjID','hr','fa')
#this dataset was not built for R so I'm doing it with python syntax
for(isubj in seq(from=1,to=nsubj))
{
  hr <- sum(posttestdf$sureHits[posttestdf$subjID==isubj])/sum(posttestdf$condLabels[posttestdf$subjID==isubj]=="Old")
  fa <- sum(posttestdf$sureFA[posttestdf$subjID==isubj])/sum(posttestdf$condLabels[posttestdf$subjID==isubj]!="Old")
  dprimedf <- rbind(dprimedf,c(isubj,hr,fa))
}
dprimedf <- dprimedf[1:nsubj+1,] #artifact of not being tidy
#dprimedf <- dprimedf[dprimedf$subjID %!in% exclude_subj,]
meanHR<-mean(dprimedf$hr)
meanFA<-mean(dprimedf$fa)
sdHR<-sd(dprimedf$hr)
sdFA<-sd(dprimedf$fa)
dprimedf <- mutate(dprimedf,dprime=norminv(dprimedf$hr,0,1)-norminv(dprimedf$fa,0,1))
#inspect dprime for all subjects to see if there's anyone we should exclude
dprimedf %>% ggplot(aes(x=subjID,y=dprime)) + geom_point() + ggtitle(paste("d' for all subjects: mean = ",as.character(mean(dprimedf$dprime))))
exclude_subj <- c(6,10) #exclude people who were clearly not trying (FA>=HR/dprime<=0)

## look at confidence on post test
labs <- (c(.1,.2,.3,.4)*length(posttestdf$respLabels))
posttestdf %>% count(respLabels) %>%
  ggplot(aes(x=respLabels,y=n)) + geom_bar(stat="identity") + ggtitle("Distribution of Post Test Confidence Ratings") + 
  scale_y_continuous(name="% of responses",breaks=labs,labels=100*c(.1,.2,.3,.4))
```

## Questionaire Data

```{r questionaire, echo=FALSE}
## look at mean VVIQ responses
VVIQdf %>% group_by(subjID) %>% summarise_at(vars(response),list(total=mean)) %>%
  ggplot(aes(x=subjID,y=total)) + geom_point() + 
  ggtitle("Total Vividness Questionaire Ratings by Subject")
```

## Behavioral Analyses

```{r replication, echo=FALSE}
#exclude based on performance
exclude_subj=c(6,10,34,35,36,37,38,39,40) #I fucked up updating the code. 
print(paste("n excluded (based on dprime being close to 0) = ",as.character(length(exclude_subj))))
#do dprime for each stimulus condition
stim_dprimedf <- data.frame(matrix(ncol=4))
colnames(stim_dprimedf) <- c('subjID','hr','fa','retrieval')
for(isubj in seq(from=1,to=nsubj))
{
  indexRet <- (posttestdf$subjID==isubj & posttestdf$retLabels=="Retrieved")
  hrRet <- as.numeric(sum(posttestdf$sureHits[indexRet])/sum(posttestdf$condLabels[indexRet]=="Old"))
  faRet <- as.numeric(sum(posttestdf$sureFA[indexRet])/sum(posttestdf$condLabels[indexRet]=="Foil"))
  stim_dprimedf <- rbind(stim_dprimedf,c(isubj,hrRet,faRet,'retrieved'))
}
for(isubj in seq(from=1,to=nsubj))
{
  indexNoRet <- (posttestdf$subjID==isubj & posttestdf$retLabels=="Not Retrieved")
  hrNoRet <- as.numeric(sum(posttestdf$sureHits[indexNoRet])/sum(posttestdf$condLabels[indexNoRet]=="Old"))
  faNoRet <- as.numeric(sum(posttestdf$sureFA[indexNoRet])/sum(posttestdf$condLabels[indexNoRet]=="Foil"))
  stim_dprimedf <- rbind(stim_dprimedf,c(isubj,hrNoRet,faNoRet,'not retrieved'))
}
stim_dprimedf <- stim_dprimedf[2:(2*nsubj+1),] #artifact of not being tidy
stim_dprimedf$hr <- as.numeric(stim_dprimedf$hr)
stim_dprimedf$fa <- as.numeric(stim_dprimedf$fa)
stim_dprimedf$subjID <- as.numeric(stim_dprimedf$subjID)
stim_dprimedf <- stim_dprimedf[stim_dprimedf$subjID %!in% exclude_subj,]
stim_dprimedf <- mutate(stim_dprimedf,dprime=(norminv(stim_dprimedf$hr,0,1)-norminv(stim_dprimedf$fa,0,1)))



#plot dprime by retrieval status
stim_dprimedf %>% group_by(retrieval) %>% summarise_at(vars(dprime),list(dmean=mean)) %>%
  ggplot(aes(x=retrieval,y=dmean,fill=retrieval))+
  geom_bar(stat="identity")+
  geom_errorbar(aes(ymin=dmean-sd(dmean),ymax=dmean+sd(dmean)),width=.2)+ggtitle('dprime retreived vs not retreived stimuli')
print(t.test(stim_dprimedf$dprime[stim_dprimedf$retrieval=='not retrieved'],stim_dprimedf$dprime[stim_dprimedf$retrieval=='retrieved']))

#plot hr and fa by retrieval status
stim_dprimedf %>% group_by(retrieval) %>% summarise_at(vars(hr),list(hr_mean=mean,hr_sd=sem)) %>% 
  ggplot(aes(x=retrieval,y=hr_mean,fill=retrieval))+geom_bar(stat="identity")+geom_bar(stat="identity")+
  geom_errorbar(aes(ymin=hr_mean-hr_sd,ymax=hr_mean+hr_sd),width=.2)+ggtitle('hr retreived vs not retreived stimuli')
print(t.test(stim_dprimedf$hr[stim_dprimedf$retrieval=='not retrieved'],stim_dprimedf$hr[stim_dprimedf$retrieval=='retrieved']))

#plot hr and fa by retrieval status
stim_dprimedf %>% group_by(retrieval) %>% summarise_at(vars(fa),list(fa_mean=mean,fa_sd=sem)) %>% 
  ggplot(aes(x=retrieval,y=fa_mean,fill=retrieval))+
  geom_bar(stat="identity")+geom_errorbar(aes(ymin=fa_mean-fa_sd,ymax=fa_mean+fa_sd),width=.2)+
  ggtitle('fa retreived vs not retreived stimuli')
print(t.test(stim_dprimedf$fa[stim_dprimedf$retrieval=='not retrieved'],stim_dprimedf$fa[stim_dprimedf$retrieval=='retrieved']))
```





```{r beh-vividness correlation set up, echo=FALSE, message=FALSE, warning=FALSE}
#my first thought is that FA and vividness are correlated
meanVVIQ <- VVIQdf %>% group_by(subjID) %>% summarise_at(vars(response),list(mean=mean))
dprimedf <- mutate(dprimedf,VVIQ=meanVVIQ$mean)

#this seems backwards
#cor.test(dprimedf$fa,dprimedf$VVIQ,method='pearson')
dprimedf %>% ggscatter(x='fa',y='VVIQ',add='reg.line',cor.coef=TRUE,cor.method='pearson',title='FA-VVIQ score correlation')

#this is a little more reasonable
#cor.test(dprimedf$dprime,dprimedf$VVIQ,method='pearson')
dprimedf %>% ggscatter(x='dprime',y='VVIQ',add='reg.line',cor.coef=TRUE,cor.method='pearson',title='dprime-VVIQ score correlation')

#lets try removing the middle subjects
label_VVIQ <- function(VVIQ)
{
  if(VVIQ<2){
    ret <- 'low'
  } else if(VVIQ>4){
    ret <- 'high'
  } else{
    ret <- 'mid'
  }
  return(ret)
}
dprimedf <- mutate(dprimedf,VVIQ_group=as.factor(unlist(lapply(dprimedf$VVIQ,label_VVIQ))))
dprimedf <- dprimedf[dprimedf$subjID %!in% exclude_subj,]
```

```{r beh-vividness correlation plotting, echo=FALSE, message=FALSE, warning=FALSE}
library(coin)
zscoreddf <- dprimedf
zscoreddf$hr <- scale(zscoreddf$hr)
zscoreddf$fa <- scale(zscoreddf$fa)
zscoreddf$dprime <- scale(zscoreddf$dprime)
#plot diff between fa/dprime for high vs low VVIQ subjects
dprimedf %>% group_by(VVIQ_group) %>% summarise_at(vars(fa),list(fa_mean=mean,fa_sd=sem)) %>% 
  ggplot(aes(x=VVIQ_group,y=fa_mean,fill=VVIQ_group)) + geom_bar(stat='identity') +
  geom_errorbar(aes(ymin=fa_mean-fa_sd,ymax=fa_mean+fa_sd),width=.2)+ggtitle('mean FA rates by VVIQ groups') +
  scale_x_discrete(limits=c('high','mid','low'))
print(t.test(dprimedf$fa[dprimedf$VVIQ_group=='high'],dprimedf$fa[dprimedf$VVIQ_group=='mid']))
print(t.test(dprimedf$fa[dprimedf$VVIQ_group=='high'],dprimedf$fa[dprimedf$VVIQ_group=='low']))
#print(oneway_test(fa~VVIQ_group,data=dprimedf,distribution=approximate(9999)))
#print(t.test(dprimedf$fa[dprimedf$VVIQ_group=='mid'],dprimedf$fa[dprimedf$VVIQ_group=='low']))
print(paste("pnorm of fa for low VVIQ subjects: ",as.character(pnorm(zscoreddf$fa[zscoreddf$VVIQ_group=='low']))))
#dprime
dprimedf %>% group_by(VVIQ_group) %>% summarise_at(vars(dprime),list(dprime_mean=mean,dprime_sd=sem)) %>% 
  ggplot(aes(x=VVIQ_group,y=dprime_mean,fill=VVIQ_group)) + geom_bar(stat='identity')+
  geom_errorbar(aes(ymin=dprime_mean-dprime_sd,ymax=dprime_mean+dprime_sd),width=.2)+ggtitle('mean dprime by VVIQ groups') +
  scale_x_discrete(limits=c('high','mid','low'))
print(t.test(dprimedf$dprime[dprimedf$VVIQ_group=='high'],dprimedf$dprime[dprimedf$VVIQ_group=='mid']))
print(t.test(dprimedf$dprime[dprimedf$VVIQ_group=='high'],dprimedf$dprime[dprimedf$VVIQ_group=='low']))
#print(oneway_test(dprime~VVIQ_group,data=dprimedf,distribution=approximate(9999)))
print(paste("pnorm of dprime for low VVIQ subjects: ",as.character(pnorm(zscoreddf$dprime[zscoreddf$VVIQ_group=='low']))))
#check HR
dprimedf %>% group_by(VVIQ_group) %>% summarise_at(vars(hr),list(hr_mean=mean,hr_sd=sem)) %>% 
  ggplot(aes(x=VVIQ_group,y=hr_mean,fill=VVIQ_group)) + geom_bar(stat='identity')+
  geom_errorbar(aes(ymin=hr_mean-hr_sd,ymax=hr_mean+hr_sd),width=.2)+ggtitle('mean HR by VVIQ groups') +
  scale_x_discrete(limits=c('high','mid','low'))
print(t.test(dprimedf$hr[dprimedf$VVIQ_group=='high'],dprimedf$hr[dprimedf$VVIQ_group=='mid']))
#tmp <- mean(dprimedf$hr[dprimedf$VVIQ_group=='low'])
print(t.test(dprimedf$hr[dprimedf$VVIQ_group=='high'],dprimedf$hr[dprimedf$VVIQ_group=='low']))
#print(oneway_test(hr~VVIQ_group,data=dprimedf,distribution=approximate(9999)))
print(paste("pnorm of hr for low VVIQ subjects: ",as.character(pnorm(zscoreddf$hr[zscoreddf$VVIQ_group=='low']))))
```


