%% script to make the mat files generated by this experiment usable

function export_mats(subjID)

wd = '/Users/kuhllabmanager/Desktop/RIME_VVIQ/Data/';

ret1FN = dir([wd,subjID,'/R1/']);
ret2FN = dir([wd,subjID,'/R2/']);
ptFN = dir([wd,subjID,'/PT/']);
stFN = dir([wd,subjID,'/study1/']);

ret1mat = load([wd,subjID,'/R1/',ret1FN(end).name]);
ret2mat = load([wd,subjID,'/R2/',ret2FN(end).name]);
ptmat = load([wd,subjID,'/PT/',ptFN(end).name]);
% something fucky is up with the vividness phases
% vividDat.vividresp = [];
% vividDat.vividRT = [];
% for i = 1:19
%     if strncmp(stFN(i).name,'RIME',4)
%         load([wd,subjID,'/study1/',stFN(i).name]);
%         tmp_resp = theData.Vivid.vividresponse_currblock;
%         vividDat.vividresp = [vividDat.vividresp,tmp_resp];
%         tmp_rt = theData.Vivid.vividRT_currblock;
%         vividDat.vividRT = [vividDat.vividRT,tmp_rt];
%     end
% end
% vividDat.vividcond = theData.Vivid.condition';
% vividDat.vividcat = theData.Vivid.category';
% vividDat.vividconID = theData.Vivid.conID';
% vividDat.vividwordID = theData.Vivid.wordID';
% vividDat.vividimageID = theData.Vivid.imageID';
load([wd,subjID,'/study1/',stFN(end).name])
studyData = theData.Study1;
retData.stimulus = [ret1mat.theData.R1.condition,ret2mat.theData.R2.condition]';
retData.conID = [ret1mat.theData.R1.conID,ret2mat.theData.R2.conID]';
retData.wordID = [ret1mat.theData.R1.wordID,ret2mat.theData.R2.wordID]';
retData.imageID = [ret1mat.theData.R1.imageID,ret2mat.theData.R2.imageID]';
retData.category = cell2mat([ret1mat.theData.R1.category,ret2mat.theData.R2.category]');
retData.response = cell2mat([ret1mat.theData.R1.vividresponse',ret2mat.theData.R2.vividresponse']');
retData.rt = cell2mat([ret1mat.theData.R1.vividRT',ret2mat.theData.R2.vividRT']');

ptData.stimulus = ptmat.theData.PT.condition';
ptData.conID = ptmat.theData.PT.conID';
ptData.wordID = ptmat.theData.PT.wordID';
ptData.imageID = ptmat.theData.PT.imageID';
ptData.category = ptmat.theData.PT.category';
ptData.response = ptmat.theData.PT.Choice';
ptData.rt = ptmat.theData.PT.RT';
ptData.hd = ptmat.theData.PT.HD';
ptData.hits = ptmat.theData.PT.Hits';
ptData.cr = ptmat.theData.PT.CR';
ptData.acc = ptmat.theData.PT.Accuracy';
ptData.sureCR = ptmat.theData.PT.sureCR';
ptData.unsureCR = ptmat.theData.PT.unsureCR';
ptData.sureHits = ptmat.theData.PT.sureHits';
for i = 1:288
    tmp = ptmat.theData.PT.conID{i}(3);
    if tmp=="I"
        ret = 1; %old
    elseif tmp=="D"
        ret = 2; %foil
    else
        ret = 3; %new
    end
    ptData.conditionID(i)=ret;
end
ptData.sureFA = (ptmat.theData.PT.Choice==4 & ptData.conditionID~=1)';
ptData.FA = ((ptmat.theData.PT.Choice==4 | ptmat.theData.PT.Choice==3) & ptData.conditionID~=1)';
ptData.conditionID=ptData.conditionID';
% ptData.dprimeSure = norminv(sum(ptData.sureHits)/sum(ptmat.theData.PT.conID(3)=="I"),0,1) - norminv(sum(ptData.sureFA)/sum(ptmat.theData.PT.conID(3)~="I"),0,1);
% ptData.dprime = norminv(sum(ptData.hits)/sum(ptmat.theData.PT.conID(3)=="I"),0,1) - norminv(sum(ptData.FA)/sum(ptmat.theData.PT.conID(3)~="I"),0,1);

mkdir([wd,subjID,'/analysisFiles/'])
save([wd,subjID,'/analysisFiles/ptData.mat'],'-struct','ptData')
save([wd,subjID,'/analysisFiles/retData.mat'],'-struct','retData')
save([wd,subjID,'/analysisFiles/studyData.mat'],'-struct','studyData')